name: CI/CD to Google Cloud with BigQuery and FASTAPI Deployment

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'

      - name: Cache pip dependencies
        uses: actions/cache@v3
        with:
          path: ~/.cache/pip
          key: ${{ runner.os }}-pip-${{ hashFiles('**/requirements.txt') }}

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip setuptools wheel
          pip install -r requirements.txt

      - name: Authenticate to Google Cloud
        uses: google-github-actions/auth@v1
        with:
          credentials_json: '${{ secrets.GCP_SA_KEY }}'

      - name: Set up Cloud SDK
        uses: google-github-actions/setup-gcloud@v1
        with:
          project_id: ${{ secrets.GCP_PROJECT_ID }}
          install_components: 'beta'

      - name: Build container image with Cloud Build
        run: |
          gcloud builds submit --tag gcr.io/${{ secrets.GCP_PROJECT_ID }}/fastapi-service .

      - name: Deploy to Cloud Run
        run: |
          gcloud run deploy fastapi-service \
            --image gcr.io/${{ secrets.GCP_PROJECT_ID }}/fastapi-service \
            --region us-central1 \
            --platform managed \
            --allow-unauthenticated
            # Optionally, specify a custom service account if needed:
            # --service-account my-cicd-service@your-project-id.iam.gserviceaccount.com
